### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by JamieP83** [custom-cards/list-card#12]
Hey,
i have data nested within a table (train times - see example below).
is it possible to draw the data out into the table, from the nesting?
eg. to show the values for the next 4 trains in a table?

i was trying the following which worked, however this card then broke other things.
```
type: 'custom:flex-table-card'
        title: Worthing to Brighton Trains
        max_rows: 10
        entities:
          exclude: null
          include: sensor.next_train_to_btn
        columns:
          - align: center
            attr_as_list: next_trains
            modify: x.status
            name: status
          - align: center
            attr_as_list: next_trains
            modify: x.scheduled
            name: scheduled
          - align: center
            attr_as_list: next_trains
            modify: x.estimated
            name: estimated
          - align: center
            attr_as_list: next_trains
            modify: x.platform
            name: platform
          - align: center
            attr_as_list: next_trains
            modify: x.destination_name
            name: destination
```

data

> {
>   "station_code": "WRH",
>   "calling_at": "BTN",
>   "next_trains": [
>     {
>       "origin_name": "Chichester",
>       "destination_name": "Brighton",
>       "status": "EARLY",
>       "scheduled": "09:26",
>       "estimated": "09:26",
>       "platform": "2",
>       "operator_name": "Southern"
>     },
>     {
>       "origin_name": "Chichester",
>       "destination_name": "Brighton",
>       "status": "ON TIME",
>       "scheduled": "09:55",
>       "estimated": "09:55",
>       "platform": "1",
>       "operator_name": "Southern"
>     },
>     {
>       "origin_name": "Chichester",
>       "destination_name": "Brighton",
>       "status": "ON TIME",
>       "scheduled": "10:26",
>       "estimated": "10:26",
>       "platform": "2",
>       "operator_name": "Southern"
>     },
>     {
>       "origin_name": "Chichester",
>       "destination_name": "Brighton",
>       "status": "ON TIME",
>       "scheduled": "10:55",
>       "estimated": "10:55",
>       "platform": "2",
>       "operator_name": "Southern"
>     }
>   ],
>   "unit_of_measurement": "min",
>   "friendly_name": "Next train to BTN",
>   "icon": "mdi:train"
> }{
  "station_code": "WRH",
  "calling_at": "BTN",
  "next_trains": [
    {
      "origin_name": "Chichester",
      "destination_name": "Brighton",
      "status": "EARLY",
      "scheduled": "09:26",
      "estimated": "09:26",
      "platform": "2",
      "operator_name": "Southern"
    },
    {
      "origin_name": "Chichester",
      "destination_name": "Brighton",
      "status": "ON TIME",
      "scheduled": "09:55",
      "estimated": "09:55",
      "platform": "1",
      "operator_name": "Southern"
    },
    {
      "origin_name": "Chichester",
      "destination_name": "Brighton",
      "status": "ON TIME",
      "scheduled": "10:26",
      "estimated": "10:26",
      "platform": "2",
      "operator_name": "Southern"
    },
    {
      "origin_name": "Chichester",
      "destination_name": "Brighton",
      "status": "ON TIME",
      "scheduled": "10:55",
      "estimated": "10:55",
      "platform": "2",
      "operator_name": "Southern"
    }
  ],
  "unit_of_measurement": "min",
  "friendly_name": "Next train to BTN",
  "icon": "mdi:train"
}
