### ISSUE TITLE
Feature request: Filter keywords to include / exclude

### ISSUE THREAD

**Issue by Amir974** [custom-cards/list-card#14]
Hi!

I am using this plugin for an RSS feed, and an awesome feature I am hoping to see is the ability to set a list of key words to include or exclude from the presented list.

If I ask for 3 lines, show only lines containing / not containing at least one of the words on the list.

Please note - my lists are in Hebrew, so encoding and language support would be also important to consider in the implementation

Hope to see this feature soon :)

**Comment by iantrich** [comment]
I'd need some guidance on that, i.e. a feedparser configuration as well as your include/exclude examples to make sure it works for Hebrew

**Comment by Amir974** [comment]
I'll try to clarify my vision if it helps:
```
 - type: custom:list-card
<Existing element properties...>
   filter:
      - include:
          - keyword1
          - keyword phrase1
          - מילת מפתח  #this is text in UTF8 for example
      - exclude:
          - keyword2
          - keyword phrase2
```

Support single / multiple words, search inside incoming entry of the feed - show / hide the entry depending if it's listed under include / exclude.

Please clarify if I can provide further information to assist :)
