### ISSUE TITLE
Only display Images

### ISSUE THREAD

**Issue by boojew** [custom-cards/list-card#17]
Is it possible to use only 1 column?  I would like to only have the image shown.

```
type: 'custom:list-card'
entity: sensor.xkcd
title: XKCD
feed_attribute: entries
columns:
  - title: '1'
    type: image
    field: image
    add_link: link
```
