### ISSUE TITLE
Unable to display images

### ISSUE THREAD

**Issue by lejvin** [custom-cards/list-card#23]
Hi, I am quite the newbie and I can't seem to figure out how to get my images to display from feedparser.

This is what my code looks like for the list:
```
columns:
  - field: title
    title: 'Title:'
  - field: summary
    title: 'Description:'
  - field: links
    title: 'Image:'
    type: image
entity: sensor.st_nu
feed_attribute: entries
row_limit: 5
type: 'custom:list-card'
```

And this is one of the entries from feedparser:

```
- title: "29-åring ny ägare till hus i Sundsvall – 1\_650\_000 kronor blev priset"
  title_detail:
    type: text/plain
    language: null
    base: 'https://www.st.nu/alla.xml'
    value: "29-åring ny ägare till hus i Sundsvall – 1\_650\_000 kronor blev priset"
  summary: "1\_650\_000 kronor fick Lars Emil Karström, 29 år, ge för huset på adressen Violvägen 4 i..."
  summary_detail:
    type: text/html
    language: null
    base: 'https://www.st.nu/alla.xml'
    value: "1\_650\_000 kronor fick Lars Emil Karström, 29 år, ge för huset på adressen Violvägen 4 i..."
  published: 'Fri, Jun 26 12:31 PM'
  links:
    - rel: alternate
      type: text/html
      href: >-
        https://www.st.nu/artikel/29-aring-ny-agare-till-hus-i-sundsvall-1-650-000-kronor-blev-priset
    - type: image/jpeg
      length: '0'
      href: >-
        https://bildix.mmcloud.se/bildix/api/images/c08e9a85-9177-4ee7-9195-d696d8b78020.jpeg?fit=crop&h=169&w=300
      rel: enclosure
  link: >-
    https://www.st.nu/artikel/29-aring-ny-agare-till-hus-i-sundsvall-1-650-000-kronor-blev-priset
  id: 12c518bb-e876-4d76-bdbd-1fb5a8be010e
  guidislink: false
  source:
    href: 'https://www.st.nu/alla.xml'
    title: Senaste nyheterna för Alla nyheter på st.nu
```

I want to display the image (in this case `https://bildix.mmcloud.se/bildix/api/images/c08e9a85-9177-4ee7-9195-d696d8b78020.jpeg?fit=crop&h=169&w=300`) in the 3rd column.

Any insight would be appreciated.

Edit: Oh, and this is what the lovelace UI looks like: 
![image](https://user-images.githubusercontent.com/62890967/85852283-8d3e0300-b7b0-11ea-9e34-5793257740cc.png)
