### ISSUE TITLE
Installed via HACS, visible in Resources, but not usable in YAML

### ISSUE THREAD

**Issue by crosenkr** [custom-cards/list-card#40]
I have a weird issue. I installed the card, and it shows in HACS and also in the Lovelace resources (as "/hacsfiles/list-card/list-card.js?hacstag=145479324011").

However, the use of the card seems not to work. I usually start with the examples, so:

- type: custom:list-card
  entity: sensor.engineering_feed
  title: Engineering Feed
  feed_attribute: entries
  columns:
    - title: Title
      field: title
    - title: Description
      field: description

But I already get "No card type configured". 

My hunch is that the resource is somehow incorrect or broken?

**Comment by IZZE2000** [comment]
same here...

**Comment by kongo09** [comment]
This assumes that you have the `feedparser` integration installed and configured with the engineering feed example. The engineering feed doesn't have a description (at least for me). Taking out the description field made it work for me.

**Comment by nolageek** [comment]
Same issue. feedparser is install and configured with engineering example. I just keep getting "No card type configured"

**Comment by Madelena** [comment]
![list-card error](https://user-images.githubusercontent.com/4341881/158487425-5a618b9a-6da1-47da-8859-ada5fb358df2.png)

Same issue here.

The config looks fine as well:
```
lovelace:
  mode: yaml
  resources:
    - url: /local/style.css
      type: css
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/compass-card/compass-card.js
      type: module
    - url: /hacsfiles/harmony-card/harmony-card.js
      type: module
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/timer-bar-card/timer-bar-card.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/uptime-card/uptime-card.js
      type: module
    - url: /hacsfiles/list-card/list-card.js
      type: module
    - url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js
      type: module
```

The js file is also in the correct path.
