### ISSUE TITLE
Feature Request: Allow templating of field

### ISSUE THREAD

**Issue by kongo09** [custom-cards/list-card#41]
The `field` attribute currently acts as a selector for the field of the feed to be displayed. It would be great if there was a possibility to apply templates to the field content.

Use case could be date formatting, where the field just contains and ISO date string but the frontend is supposed to display something nicer.

Extension: the `field` attribute could take more than one field, which then could be combined in a template.

Use case could be two data fields that are displayed in only one column. As a special case you do this already with the icons and the links.

**Comment by brylee123** [comment]
I would like to second this. Sometimes there's redundant information and I just want to filter it out.

**Comment by netsoft-ruidias** [comment]
use this fork: https://github.com/netsoft-ruidias/lovelace-list-card for templates

Then, you can use templates like this:
```yaml
type: custom:list-card
entity: sensor.edenred_card
feed_attribute: transactions
row_limit: 25
columns:
  - title: Date
    field: date
    template: |
      [[[ return new Date(entry.date).toLocaleDateString('pt-PT'); ]]]
    style:
      - padding: 5px
      - color: var(--secondary-text-color);
  - title: Movement
    field: name
    template: |
      [[[ return entry.name.replace('Compra: ', ''); ]]]
    style:
      - padding: 5px
      - color: var(--secondary-text-color);
      - text-align: left;
      - white-space: nowrap;
      - overflow: hidden;
      - text-overflow: ellipsis;
  - title: Euros
    field: amount
    template: |
      [[[ return entry.amount.toFixed(2) + ' €'; ]]]
    style:
      - text-align: right
      - white-space: nowrap
      - padding: 5px
```
