### ISSUE TITLE
Regex option - could you add more info/examples in readme?

### ISSUE THREAD

**Issue by rpitera** [custom-cards/list-card#5]
First, thank you for this card and component. I am finally able to use RSS the way I've wanted in my HA install.  It was what I had hoped the stock RSS component would do but never did.  Bless you, sir!!  

But I am not quite sure what the regex option does and if it would allow me to filter out entries in the list table.  When you get a chance could you elaborate a little more in the docs on usage and perhaps provide an example or two?

If this can be used as a filter, this would solve an issue for me but I'm not sure how to go about it.  I'd like to filter out any entry beginning with "NYSTA" or "NYSDOT" but not sure if understanding how this works would be the answer or not.

Thanks again for an awesome feature enhancement to HA!

**Comment by iantrich** [comment]
The regex feature currently is just for display of the field in question, it does not filter actual entries based on any regex, currently.

**Comment by rpitera** [comment]
Bummer.  Still would like to know more about how it works, even if it doesn't solve my problem.  I have to assume you had a good reason for including it as a feature in the original release and it seems a shame for me not to put it to use! :)

**Comment by iantrich** [comment]
Here's an example from my personal configuration:

```
              - type: custom:list-card
                entity: sensor.upcoming_shows
                title: Upcoming Shows
                columns:
                  - title: ''
                    field: title
                    regex: >-
                      [0-9]{1,2}[Xx][0-9]{1,2}
```
Which takes a string like `Manifest 1x06 "Off Radar"` and gives everything after the season/episode numbers, i.e. the title of the show `"Off Radar"`

It's just 100% regex matching against a string
