### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Bluscream** [custom-cards/list-card#57]
Feed:
```yml
# feedreader:
#   urls:
#     - https://www.home-assistant.io/atom.xml
#     - https://merkurist.de/mainz/Newsfeed

sensor:
  platform: feedparser
  name: Merkurist Mainz
  feed_url: "https://merkurist.de/mainz/Newsfeed"
  date_format:
    "%a, %d %b %Y %H:%M:%S %Z"
    # Sun, 14 Apr 2024 17:29:38 GMT
  scan_interval:
    hours: 1
  inclusions:
    - title
    - link
    - description
    - image
    - pubDate
  # exclusions:
  #   - language
```

Error / Card
```yml
type: custom:list-card
entity: sensor.merkurist_mainz
title: Merkurist
feed_attribute: Entries
columns:
  - title: ''
    type: image
    add_link: link
    field: image
  - title: Title
    field: title
    style:
      - white-space: nowrap
```
